from pathlib import Path
p=Path('src/components/admin-appointments-workspace.tsx')
s=p.read_text()
s=s.replace('  const [serviceIds, setServiceIds] = useState<string[]>([]);\n', '  const [serviceIds, setServiceIds] = useState<string[]>([]);\n  const [serviceSearch, setServiceSearch] = useState(\"\");\n')
s=s.replace('  const selectedServices = useMemo(\n    () => serviceIds.map((id) => services.find((service) => service.id === id)).filter(Boolean),\n    [serviceIds, services],\n  );\n', '  const selectedServices = useMemo(\n    () => serviceIds.map((id) => services.find((service) => service.id === id)).filter(Boolean),\n    [serviceIds, services],\n  );\n\n  const filteredServices = useMemo(() => {\n    const term = serviceSearch.trim().toLocaleLowerCase(\"pt-BR\");\n    if (!term) return services;\n    return services.filter((service) => String(service.name ?? \"\").toLocaleLowerCase(\"pt-BR\").includes(term));\n  }, [services, serviceSearch]);\n')
s=s.replace('  const reset = () => { setSelectedClientId(\"\"); setPatientName(\"\"); setPatientEmail(\"\"); setPatientPhone(\"\"); setServiceIds([]); setAppointmentValue(\"\"); setProfessionalId(\"\"); setScheduledDate(todayIso()); setScheduledTime(\"\"); setNotes(\"\"); };', '  const reset = () => { setSelectedClientId(\"\"); setPatientName(\"\"); setPatientEmail(\"\"); setPatientPhone(\"\"); setServiceIds([]); setServiceSearch(\"\"); setAppointmentValue(\"\"); setProfessionalId(\"\"); setScheduledDate(todayIso()); setScheduledTime(\"\"); setNotes(\"\"); };')
old='''      <div className="grid max-h-52 gap-2 overflow-y-auto rounded-2xl border border-border bg-background p-2 sm:grid-cols-2">\n        {services.map((service) => { const checked = serviceIds.includes(service.id); return <button key={service.id} type="button" disabled={saving || loadingCatalog} onClick={() => toggleService(service.id)} className={`flex items-center justify-between gap-3 rounded-xl border px-3 py-2.5 text-left transition ${checked ? "border-primary bg-primary-soft/70 text-primary" : "border-border bg-card hover:bg-secondary/40"}`}><span className="min-w-0"><span className="block truncate text-sm font-medium">{service.name}</span><span className="mt-0.5 block text-[11px] text-muted-foreground">{formatPrice(Number(service.price ?? 0))}</span></span><span className={`grid size-6 shrink-0 place-items-center rounded-lg border ${checked ? "border-primary bg-primary text-primary-foreground" : "border-border bg-background"}`}>{checked ? <Check className="size-3.5" /> : null}</span></button>; })}\n      </div>'''
new='''      <div className="rounded-2xl border border-border bg-background p-2">\n        <div className="relative mb-2">\n          <Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />\n          <Input value={serviceSearch} onChange={(event) => setServiceSearch(event.target.value)} placeholder="Buscar serviço..." className="h-9 rounded-xl pl-9 text-sm" disabled={saving || loadingCatalog} />\n        </div>\n        <div className="grid max-h-52 gap-2 overflow-y-auto sm:grid-cols-2">\n          {filteredServices.length ? filteredServices.map((service) => { const checked = serviceIds.includes(service.id); return <button key={service.id} type="button" disabled={saving || loadingCatalog} onClick={() => toggleService(service.id)} className={`flex items-center justify-between gap-3 rounded-xl border px-3 py-2.5 text-left transition ${checked ? "border-primary bg-primary-soft/70 text-primary" : "border-border bg-card hover:bg-secondary/40"}`}><span className="min-w-0"><span className="block truncate text-sm font-medium">{service.name}</span><span className="mt-0.5 block text-[11px] text-muted-foreground">{formatPrice(Number(service.price ?? 0))}</span></span><span className={`grid size-6 shrink-0 place-items-center rounded-lg border ${checked ? "border-primary bg-primary text-primary-foreground" : "border-border bg-background"}`}>{checked ? <Check className="size-3.5" /> : null}</span></button>; }) : <div className="py-5 text-center text-xs text-muted-foreground sm:col-span-2">Nenhum serviço encontrado.</div>}\n        </div>\n      </div>'''
if old not in s: raise SystemExit('target not found')
s=s.replace(old,new)
p.write_text(s)
