from pathlib import Path

p = Path('src/components/admin-appointments-workspace.tsx')
s = p.read_text()

old = '''      const detail = await fetchAppointment(next.id);\n      if (!detail) return;\n      playNotificationSound(audioRef);\n      setIncoming(detail);'''
new = '''      const detail = await fetchAppointment(next.id);\n      if (!detail) return;\n      // Never stack the realtime alert over the creation dialog. Two Radix overlays\n      // made the whole page almost black and could also distort the alert layout.\n      setCreateOpen(false);\n      playNotificationSound(audioRef);\n      setIncoming(detail);'''
if old not in s:
    raise SystemExit('notify block not found')
s = s.replace(old, new, 1)

old2 = '''function NewAppointmentAlert({ appointment, open, onLater, onConfirm, onCancel, busy }: any) {\n  if (!appointment) return null;\n  const hasWhatsApp = normalizeWhatsAppPhone(appointment.patient_phone).length > 0;\n  return <Dialog open={open} onOpenChange={(next) => !next && onLater()}><DialogContent className="w-[calc(100%-1rem)] rounded-3xl p-5 sm:max-w-md sm:p-6"><DialogHeader><span className="mb-2 grid size-12 place-items-center rounded-2xl bg-primary-soft text-primary"><BellRing className="size-5" /></span><DialogTitle>Novo agendamento realizado</DialogTitle><DialogDescription>A profissional ainda precisa confirmar este atendimento.</DialogDescription></DialogHeader><div className="mt-2 rounded-2xl border border-border bg-secondary/40 p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate font-semibold">{appointment.patient_name}</p><p className="mt-1 truncate text-xs text-muted-foreground">{appointment.service?.name ?? "Atendimento"}</p></div><AdminStatusBadge status={appointment.status} /></div><div className="mt-3 grid grid-cols-2 gap-2"><SmallInfo label="Data" value={formatDate(appointment.scheduled_date)} /><SmallInfo label="Horário" value={appointment.scheduled_time} /><SmallInfo label="Profissional" value={appointment.professional?.name ?? "—"} /><SmallInfo label="Pagamento" value={paymentLabel(appointment)} accent /></div></div>{hasWhatsApp ? <Button variant="outline" className="mt-3 w-full rounded-xl border-emerald-600/40 text-emerald-700" onClick={() => openAppointmentWhatsApp(appointment, "confirmation")}><MessageCircle className="size-4" /> Confirmar pelo WhatsApp</Button> : null}<DialogFooter className="mt-4 grid grid-cols-1 gap-2 sm:grid-cols-3 sm:space-x-0"><Button variant="outline" disabled={busy} onClick={onLater}>Depois</Button><Button variant="destructive" disabled={busy} onClick={onCancel}>Cancelar</Button><Button disabled={busy} onClick={onConfirm}>Confirmar</Button></DialogFooter></DialogContent></Dialog>;\n}'''
new2 = '''function NewAppointmentAlert({ appointment, open, onLater, onConfirm, onCancel, busy }: any) {\n  if (!appointment) return null;\n  const hasWhatsApp = normalizeWhatsAppPhone(appointment.patient_phone).length > 0;\n  const servicesLabel = appointmentServicesLabel(appointment);\n  return (\n    <Dialog open={open} onOpenChange={(next) => !next && onLater()}>\n      <DialogContent className="w-[calc(100vw-1.5rem)] max-w-[460px] min-w-0 overflow-hidden rounded-3xl p-5 sm:p-6">\n        <DialogHeader className="min-w-0 pr-7">\n          <span className="mb-2 grid size-11 place-items-center rounded-2xl bg-primary-soft text-primary"><BellRing className="size-5" /></span>\n          <DialogTitle>Novo agendamento realizado</DialogTitle>\n          <DialogDescription>A profissional ainda precisa confirmar este atendimento.</DialogDescription>\n        </DialogHeader>\n        <div className="mt-1 min-w-0 max-w-full overflow-hidden rounded-2xl border border-border bg-secondary/40 p-4">\n          <div className="flex min-w-0 items-start justify-between gap-3">\n            <div className="min-w-0 flex-1">\n              <p className="truncate font-semibold">{appointment.patient_name}</p>\n              <p className="mt-1 line-clamp-2 break-words text-xs leading-relaxed text-muted-foreground">{servicesLabel}</p>\n            </div>\n            <AdminStatusBadge status={appointment.status} />\n          </div>\n          <div className="mt-3 grid min-w-0 grid-cols-2 gap-3">\n            <SmallInfo label="Data" value={formatDate(appointment.scheduled_date)} />\n            <SmallInfo label="Horário" value={appointment.scheduled_time} />\n            <SmallInfo label="Profissional" value={appointment.professional?.name ?? "—"} />\n            <SmallInfo label="Pagamento" value={paymentLabel(appointment)} accent />\n          </div>\n        </div>\n        {hasWhatsApp ? <Button variant="outline" className="mt-1 w-full max-w-full rounded-xl border-emerald-600/40 text-emerald-700" onClick={() => openAppointmentWhatsApp(appointment, "confirmation")}><MessageCircle className="size-4" /> Confirmar pelo WhatsApp</Button> : null}\n        <DialogFooter className="mt-1 grid w-full min-w-0 grid-cols-1 gap-2 sm:grid-cols-3 sm:space-x-0">\n          <Button className="w-full" variant="outline" disabled={busy} onClick={onLater}>Depois</Button>\n          <Button className="w-full" variant="destructive" disabled={busy} onClick={onCancel}>Cancelar</Button>\n          <Button className="w-full" disabled={busy} onClick={onConfirm}>Confirmar</Button>\n        </DialogFooter>\n      </DialogContent>\n    </Dialog>\n  );\n}'''
if old2 not in s:
    raise SystemExit('alert block not found')
s = s.replace(old2, new2, 1)

# Make the service search unmistakably visible and sticky above the scrollable list.
old3 = '''        <div className="relative mb-2">\n          <Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />\n          <Input value={serviceSearch} onChange={(event) => setServiceSearch(event.target.value)} placeholder="Buscar serviço..." className="h-9 rounded-xl pl-9 text-sm" disabled={saving || loadingCatalog} />\n        </div>'''
new3 = '''        <div className="sticky top-0 z-10 mb-2 bg-background pb-1">\n          <div className="relative">\n            <Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-primary/70" />\n            <Input value={serviceSearch} onChange={(event) => setServiceSearch(event.target.value)} placeholder="Pesquisar procedimento..." className="h-10 rounded-xl border-primary/25 bg-card pl-9 pr-3 text-sm shadow-sm focus-visible:ring-primary/25" disabled={saving || loadingCatalog} />\n          </div>\n        </div>'''
if old3 not in s:
    raise SystemExit('search block not found')
s = s.replace(old3, new3, 1)
p.write_text(s)

p2 = Path('src/components/ui/dialog.tsx')
d = p2.read_text()
d = d.replace('"fixed inset-0 z-50 bg-black/80  data-[state=open]:animate-in', '"fixed inset-0 z-50 bg-black/40 backdrop-blur-[1px] data-[state=open]:animate-in')
p2.write_text(d)
